version: '3.8'
services:
  chandu-ui-code: # name of app change it 
    image: chandu-web-app:appv$BUILD_NUMBER
    build:
      context: . # location of dockerfile 
      dockerfile: Dockerfile # name of dockerfile 
    container_name: chandu-web-d1 
    ports:
      - 1223:80 # left side port b/w 1024 - 5000 
